### ISSUE TITLE
bootstrap.effectivemass should include which time indices are valid

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/hadron#146]
@matfischer had a good idea to make interaction with his Bayesian fitting routines more straightforward.
In addition to ```t.idx```, ```bootstrap.effectivemass``` should produce a second vector of indices which can be used to subset the "valid" time slices of the effective mass, i.e., those which are not ```NA```. Since this depends on the type, it is good for ```boostrap.effectivemass``` to do this rather than having to externally check which effective mass type was used and making the appropriate externally.

**Comment by martin-ueding** [comment]
So basically we want a vector like that returned by `bootstrap.effectivemass`, depending on the `type` case? This is for the `samplecf`.

```
$solve
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

$acosh
 [1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[23]  TRUE  TRUE

$temporal
 [1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[23]  TRUE FALSE

$log
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

$shifted
 [1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[23]  TRUE FALSE

$shifted
 [1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[23]  TRUE FALSE
```

**Comment by matfischer** [comment]
Yes, as Bartek pointed out, that is basically what I had in mind. But this vector should contain TRUE or FALSE for time slices in between as well, so that we get a vector which contains only valid time slices which can be related directly to the corresponding time slice. Let t <- 0:T/2, then: t[samplecf] = 1 2 4 ... T/2 -1, e.g.

This would make the "interface" easier between hadron and my BayesianFitting package. At the moment I do this externally but if there is general interest in extending the returned list of bootstrap.effective mass that would be a nice feature.

**Comment by martin-ueding** [comment]
> But this vector should contain TRUE or FALSE for time slices in between as well

I think I do not understand. This vector is as long as the effective mass has entries. So it has entries for all the time slices in between.

Shall I return `FALSE` for all the slices which contain `NA` on some time slices?

**Comment by matfischer** [comment]
Yes, that was the idea. So you just have to apply this vector to the t range of the correlator and get the "x"-values which are well defined and thus you can truncate the "y"-values as well.

**Comment by martin-ueding** [comment]
But then why don't just do `!is.na(effmass$effMass)` yourself?

**Comment by matfischer** [comment]
Since I thought to get the valid "x"- and "y"-values directly from `bootstrap.effectivemass` as we get t.idx. `!is.na(effmass$effMass)` is the way I do it atm. We don't have to change it. It was more or less a general question if there is any further interest in appending the `bootstrap.effectivemass` list.

**Comment by martin-ueding** [comment]
> It was more or less a general question if there is any further interest in appending the `bootstrap.effectivemass` list.

In general I would like to avoid any such appendices. It would violate the SRP of [SOLID](https://en.wikipedia.org/wiki/SOLID), if not perhaps also the OCP.

So basically you want to have this function to give you the valid time slices?

```r
remove_NA.effectivemass <- function (effmass, na.rm = FALSE) {
  valid <- !is.na(effmass$effMass)
  val <- with(effmass, data.frame(t.idx = t.idx, effMass = effMass, deffMass = deffMass)[valid, ])
  boot <- effmass$effMass.tsboot[, valid]
  if (na.rm) {
    cc <- complete.cases(boot)
    boot <- boot[cc, ]
  }
  list(val = val, boot = boot)
}
```

**Comment by kostrzewa** [comment]
Do not apply ```complete.cases``` to ```boot```. Technically you need to resample if there are ```NA``` in the bootstrap samples. If there are too many ```NA```s, you need to remove the entire time-slice. See ```effectivemass.cf```.

**Comment by matfischer** [comment]
Yes, at the moment I use two functions which are similar to yours since I create the df which contains (x,y,dy) and the covariance matrix separately. I would say, we leave everything as it is and I do this outside of hadron, except there is anyone else interested in implementing such a function inside hadron. But thanks for looking at it @martin-ueding .

**Comment by martin-ueding** [comment]
I would suggest that you add a file `R/towards_hadron.R` in your package with functionality which could eventually be included in the hadron library. This way you can evolve it to your needs at first and we can include it later for everyone to use.
